sudo: required
services:
  - docker

before_install:
  - docker build -t algosdev/docker-react -f Dockerfile.dev .

script:
  - docker run algosdev/docker-react npm run test:prod -- --coverage

deploy:
  provider: elasticbeanstalk
  region: "ap-northeast-1"
  app: "docker-react"
  env: "Dockerreact-env"
  bucket_name: "elasticbeanstalk-ap-northeast-1-614098318322"
  bucket_path: "docker-react"
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: "$AWS_SECRET_KEY"